services:
  arango:
    image: arangodb:latest
    container_name: arango
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD:-your_password}
    ports:
      - "8529:8529"
    volumes:
      - ./data/arangodb:/var/lib/arangodb3
    restart: unless-stopped
